<?php

function layout_theme($existing, $type, $theme, $path) {
    return [
        'header_block'=>[
            'template'=>'header',
            'variables'=>[
                'data' => [],
            ]
            ],
            'footer_block'=>[
                'template'=>'footer',
                'variables'=>[
                    'data' => [],
                ]
                ],
            'slider_block'=>[
                'template'=>'slider',
                'variables'=>[
               'data' => [],
                    ]
                    ]
            ];
}
